-- ArchiCompass Admin Workspace.
-- Keeps staff access separate from editable user profiles and exposes only
-- sanitized operational data. Private messages and reference photos are not
-- returned by these functions.

begin;

create table if not exists public.admin_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'support', 'content', 'finance')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.admin_user_reviews (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'clear'
    check (status in ('clear', 'needs_review', 'priority')),
  internal_note text check (internal_note is null or char_length(internal_note) <= 4000),
  updated_at timestamptz not null default now(),
  updated_by uuid not null references auth.users(id) on delete restrict
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log (created_at desc);

alter table public.admin_roles enable row level security;
alter table public.admin_user_reviews enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on public.admin_roles from anon, authenticated;
revoke all on public.admin_user_reviews from anon, authenticated;
revoke all on public.admin_audit_log from anon, authenticated;

grant select on public.admin_roles to authenticated;
grant select on public.admin_user_reviews to authenticated;
grant select on public.admin_audit_log to authenticated;

drop policy if exists "admin_roles_select_own" on public.admin_roles;
create policy "admin_roles_select_own"
on public.admin_roles
for select
to authenticated
using (user_id = auth.uid() and active);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.admin_roles role_record
    where role_record.user_id = auth.uid()
      and role_record.active
      and role_record.role in ('owner', 'admin')
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "admin_user_reviews_select_admin" on public.admin_user_reviews;
create policy "admin_user_reviews_select_admin"
on public.admin_user_reviews
for select
to authenticated
using (public.is_admin());

drop policy if exists "admin_audit_log_select_admin" on public.admin_audit_log;
create policy "admin_audit_log_select_admin"
on public.admin_audit_log
for select
to authenticated
using (public.is_admin());

create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'users', (select count(*) from auth.users),
    'profiles', (select count(*) from public.profiles),
    'professionals', (
      select count(*)
      from public.profiles profile_record
      where profile_record.user_type = 'professional'
        or nullif(trim(profile_record.profession_type), '') is not null
    ),
    'clients', (
      select count(*)
      from auth.users user_record
      left join public.profiles profile_record on profile_record.id = user_record.id
      where coalesce(profile_record.user_type, 'client') <> 'professional'
        and nullif(trim(profile_record.profession_type), '') is null
    ),
    'projects', (select count(*) from public.projects),
    'briefs', (select count(*) from public.project_briefs),
    'inquiries', (select count(*) from public.designer_inquiries),
    'favorites', (select count(*) from public.favorites),
    'signups_30', (
      select count(*) from auth.users where created_at >= now() - interval '30 days'
    ),
    'active_30', (
      select count(*) from auth.users where last_sign_in_at >= now() - interval '30 days'
    ),
    'profile_views_30', (
      select count(*) from public.profile_views where created_at >= now() - interval '30 days'
    )
  );
end;
$$;

create or replace function public.admin_user_directory(
  search_text text default null,
  account_type text default 'all',
  review_filter text default 'all',
  page_limit integer default 50,
  page_offset integer default 0
)
returns table (
  user_id uuid,
  email text,
  full_name text,
  user_type text,
  profession_type text,
  location text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  project_count bigint,
  brief_count bigint,
  sent_inquiry_count bigint,
  received_inquiry_count bigint,
  review_status text,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  return query
  select
    user_record.id,
    user_record.email::text,
    profile_record.full_name,
    profile_record.user_type,
    profile_record.profession_type,
    profile_record.location,
    user_record.created_at,
    user_record.last_sign_in_at,
    (select count(*) from public.projects project_record where project_record.profile_id = user_record.id),
    (select count(*) from public.project_briefs brief_record where brief_record.user_id = user_record.id),
    (select count(*) from public.designer_inquiries inquiry_record where inquiry_record.client_id = user_record.id),
    (select count(*) from public.designer_inquiries inquiry_record where inquiry_record.designer_id = user_record.id),
    coalesce(review_record.status, 'clear'),
    count(*) over()
  from auth.users user_record
  left join public.profiles profile_record on profile_record.id = user_record.id
  left join public.admin_user_reviews review_record on review_record.user_id = user_record.id
  where (
    nullif(trim(coalesce(search_text, '')), '') is null
    or user_record.email ilike '%' || trim(search_text) || '%'
    or coalesce(profile_record.full_name, '') ilike '%' || trim(search_text) || '%'
    or coalesce(profile_record.location, '') ilike '%' || trim(search_text) || '%'
  )
  and (
    account_type = 'all'
    or (account_type = 'professional' and (
      profile_record.user_type = 'professional'
      or nullif(trim(profile_record.profession_type), '') is not null
    ))
    or (account_type = 'client' and (
      coalesce(profile_record.user_type, 'client') <> 'professional'
      and nullif(trim(profile_record.profession_type), '') is null
    ))
    or (account_type = 'no_profile' and profile_record.id is null)
  )
  and (
    review_filter = 'all'
    or coalesce(review_record.status, 'clear') = review_filter
  )
  order by user_record.created_at desc
  limit greatest(1, least(coalesce(page_limit, 50), 100))
  offset greatest(0, coalesce(page_offset, 0));
end;
$$;

create or replace function public.admin_user_detail(target_user_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'user_id', user_record.id,
    'email', user_record.email,
    'created_at', user_record.created_at,
    'last_sign_in_at', user_record.last_sign_in_at,
    'profile', jsonb_build_object(
      'full_name', profile_record.full_name,
      'bio', profile_record.bio,
      'location', profile_record.location,
      'profession_type', profile_record.profession_type,
      'user_type', profile_record.user_type,
      'specialties', coalesce(profile_record.specialties, '{}'::text[]),
      'website', profile_record.website,
      'phone', profile_record.phone,
      'email', profile_record.email,
      'hourly_rate', profile_record.hourly_rate,
      'years_experience', profile_record.years_experience
    ),
    'counts', jsonb_build_object(
      'projects', (select count(*) from public.projects where profile_id = user_record.id),
      'briefs', (select count(*) from public.project_briefs where user_id = user_record.id),
      'sent_inquiries', (select count(*) from public.designer_inquiries where client_id = user_record.id),
      'received_inquiries', (select count(*) from public.designer_inquiries where designer_id = user_record.id),
      'favorites', (select count(*) from public.favorites where user_id = user_record.id),
      'profile_views', (select count(*) from public.profile_views where profile_id = user_record.id)
    ),
    'projects', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', project_record.id,
          'title', project_record.title,
          'category', project_record.category,
          'created_at', project_record.created_at
        ) order by project_record.created_at desc
      )
      from public.projects project_record
      where project_record.profile_id = user_record.id
    ), '[]'::jsonb),
    'review', jsonb_build_object(
      'status', coalesce(review_record.status, 'clear'),
      'internal_note', review_record.internal_note,
      'updated_at', review_record.updated_at,
      'updated_by', review_record.updated_by
    ),
    'admin_role', role_record.role
  )
  into result
  from auth.users user_record
  left join public.profiles profile_record on profile_record.id = user_record.id
  left join public.admin_user_reviews review_record on review_record.user_id = user_record.id
  left join public.admin_roles role_record
    on role_record.user_id = user_record.id and role_record.active
  where user_record.id = target_user_id;

  return result;
end;
$$;

create or replace function public.admin_set_user_review(
  target_user_id uuid,
  review_status text,
  review_note text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  if review_status not in ('clear', 'needs_review', 'priority') then
    raise exception 'Invalid review status' using errcode = '22023';
  end if;

  if not exists (select 1 from auth.users where id = target_user_id) then
    raise exception 'User not found' using errcode = 'P0002';
  end if;

  insert into public.admin_user_reviews (
    user_id,
    status,
    internal_note,
    updated_at,
    updated_by
  )
  values (
    target_user_id,
    review_status,
    nullif(trim(coalesce(review_note, '')), ''),
    now(),
    auth.uid()
  )
  on conflict (user_id) do update
  set
    status = excluded.status,
    internal_note = excluded.internal_note,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by;

  insert into public.admin_audit_log (
    actor_id,
    action,
    target_type,
    target_id,
    metadata
  )
  values (
    auth.uid(),
    'user_review_updated',
    'user',
    target_user_id::text,
    jsonb_build_object('status', review_status)
  );
end;
$$;

create or replace function public.admin_activity_feed(page_limit integer default 50)
returns table (
  id bigint,
  actor_id uuid,
  actor_email text,
  action text,
  target_type text,
  target_id text,
  metadata jsonb,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  return query
  select
    audit_record.id,
    audit_record.actor_id,
    user_record.email::text,
    audit_record.action,
    audit_record.target_type,
    audit_record.target_id,
    audit_record.metadata,
    audit_record.created_at
  from public.admin_audit_log audit_record
  left join auth.users user_record on user_record.id = audit_record.actor_id
  order by audit_record.created_at desc
  limit greatest(1, least(coalesce(page_limit, 50), 200));
end;
$$;

revoke all on function public.admin_dashboard_stats() from public;
revoke all on function public.admin_user_directory(text, text, text, integer, integer) from public;
revoke all on function public.admin_user_detail(uuid) from public;
revoke all on function public.admin_set_user_review(uuid, text, text) from public;
revoke all on function public.admin_activity_feed(integer) from public;

grant execute on function public.admin_dashboard_stats() to authenticated;
grant execute on function public.admin_user_directory(text, text, text, integer, integer) to authenticated;
grant execute on function public.admin_user_detail(uuid) to authenticated;
grant execute on function public.admin_set_user_review(uuid, text, text) to authenticated;
grant execute on function public.admin_activity_feed(integer) to authenticated;

-- Initial owner account for the closed beta.
insert into public.admin_roles (user_id, role, active, created_by)
select user_record.id, 'owner', true, user_record.id
from auth.users user_record
where user_record.id = 'bfd0b136-8bf6-4d49-be53-ef2a6dce7030'::uuid
on conflict (user_id) do update
set role = excluded.role, active = true;

commit;
