-- Designer Studio: inquiry conversations and privacy-light profile analytics.
-- Run after `supabase/designer-inquiries.sql`.

begin;

create table if not exists public.inquiry_messages (
  id uuid primary key default gen_random_uuid(),
  inquiry_id uuid not null references public.designer_inquiries(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists inquiry_messages_inquiry_idx
on public.inquiry_messages (inquiry_id, created_at asc);

create index if not exists inquiry_messages_unread_idx
on public.inquiry_messages (inquiry_id, sender_id, read_at)
where read_at is null;

alter table public.inquiry_messages enable row level security;

drop policy if exists "inquiry_messages_select_participants" on public.inquiry_messages;
create policy "inquiry_messages_select_participants"
on public.inquiry_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.designer_inquiries inquiry
    where inquiry.id = inquiry_messages.inquiry_id
      and (inquiry.client_id = auth.uid() or inquiry.designer_id = auth.uid())
  )
);

drop policy if exists "inquiry_messages_insert_participants" on public.inquiry_messages;
create policy "inquiry_messages_insert_participants"
on public.inquiry_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.designer_inquiries inquiry
    where inquiry.id = inquiry_messages.inquiry_id
      and (inquiry.client_id = auth.uid() or inquiry.designer_id = auth.uid())
  )
);

drop policy if exists "inquiry_messages_mark_received_read" on public.inquiry_messages;
create policy "inquiry_messages_mark_received_read"
on public.inquiry_messages
for update
to authenticated
using (
  sender_id <> auth.uid()
  and exists (
    select 1
    from public.designer_inquiries inquiry
    where inquiry.id = inquiry_messages.inquiry_id
      and (inquiry.client_id = auth.uid() or inquiry.designer_id = auth.uid())
  )
)
with check (
  sender_id <> auth.uid()
  and exists (
    select 1
    from public.designer_inquiries inquiry
    where inquiry.id = inquiry_messages.inquiry_id
      and (inquiry.client_id = auth.uid() or inquiry.designer_id = auth.uid())
  )
);

revoke all on public.inquiry_messages from anon, authenticated;
grant select, insert on public.inquiry_messages to authenticated;
grant update (read_at) on public.inquiry_messages to authenticated;

create table if not exists public.profile_views (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  session_key text not null check (char_length(session_key) between 20 and 100),
  source_path text not null default '',
  view_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (profile_id, session_key, view_date)
);

create index if not exists profile_views_profile_created_idx
on public.profile_views (profile_id, created_at desc);

alter table public.profile_views enable row level security;

drop policy if exists "profile_views_insert_public" on public.profile_views;
create policy "profile_views_insert_public"
on public.profile_views
for insert
to anon, authenticated
with check (
  char_length(session_key) between 20 and 100
  and char_length(source_path) <= 500
  and exists (
    select 1 from public.profiles where profiles.id = profile_views.profile_id
  )
);

drop policy if exists "profile_views_select_owner" on public.profile_views;
create policy "profile_views_select_owner"
on public.profile_views
for select
to authenticated
using (profile_id = auth.uid());

drop policy if exists "profile_views_delete_owner" on public.profile_views;
create policy "profile_views_delete_owner"
on public.profile_views
for delete
to authenticated
using (profile_id = auth.uid());

revoke all on public.profile_views from anon, authenticated;
grant insert on public.profile_views to anon, authenticated;
grant select, delete on public.profile_views to authenticated;
grant usage, select on sequence public.profile_views_id_seq to anon, authenticated;

commit;
