-- Record and enforce the mandatory legal-document confirmations collected during sign-up.
-- The auth trigger makes this requirement apply even if the browser UI is bypassed.
begin;

create schema if not exists private;
revoke all on schema private from public;

create table if not exists public.legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  cookies_version text not null,
  ai_transparency_version text not null,
  terms_accepted_at timestamptz not null default now(),
  privacy_acknowledged_at timestamptz not null default now(),
  accepted_locale text not null check (accepted_locale in ('pl', 'en')),
  accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, terms_version, privacy_version, cookies_version, ai_transparency_version)
);

alter table public.legal_acceptances enable row level security;

revoke all on table public.legal_acceptances from public, anon, authenticated;
grant select on table public.legal_acceptances to authenticated;

drop policy if exists "Users can read own legal acceptances" on public.legal_acceptances;
create policy "Users can read own legal acceptances"
  on public.legal_acceptances
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function private.capture_required_legal_acceptance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  acceptance jsonb := coalesce(new.raw_user_meta_data -> 'legal_acceptance', '{}'::jsonb);
  required_version constant text := '2026-08-28';
begin
  if acceptance ->> 'terms_version' <> required_version
    or acceptance ->> 'privacy_version' <> required_version
    or acceptance ->> 'cookies_version' <> required_version
    or acceptance ->> 'ai_transparency_version' <> required_version
    or acceptance ->> 'terms_accepted' <> 'true'
    or acceptance ->> 'privacy_acknowledged' <> 'true'
    or acceptance ->> 'locale' not in ('pl', 'en') then
    raise exception using
      errcode = 'P0001',
      message = 'Required legal document confirmations are missing or invalid.';
  end if;

  insert into public.legal_acceptances (
    user_id,
    terms_version,
    privacy_version,
    cookies_version,
    ai_transparency_version,
    terms_accepted_at,
    privacy_acknowledged_at,
    accepted_locale
  )
  values (
    new.id,
    acceptance ->> 'terms_version',
    acceptance ->> 'privacy_version',
    acceptance ->> 'cookies_version',
    acceptance ->> 'ai_transparency_version',
    now(),
    now(),
    acceptance ->> 'locale'
  )
  on conflict (user_id, terms_version, privacy_version, cookies_version, ai_transparency_version)
  do nothing;

  return new;
end;
$$;

revoke all on function private.capture_required_legal_acceptance() from public, anon, authenticated;
grant usage on schema private to supabase_auth_admin;
grant execute on function private.capture_required_legal_acceptance() to supabase_auth_admin;

drop trigger if exists users_capture_required_legal_acceptance on auth.users;
create trigger users_capture_required_legal_acceptance
  after insert on auth.users
  for each row
  execute procedure private.capture_required_legal_acceptance();

commit;
