import { siteLocale, type SiteLocale } from "@/lib/site-locale";

const copy = {
  pl: {
    notFoundTitle: "Nie znaleziono lokalizacji",
    notFoundDescription: "Ta lokalizacja nie jest dostępna.",
    home: "Strona główna",
    directory: "Katalog Projektantów",
    directoryLink: "Znajdź projektantów",
    directoryBadge: "Katalog projektantów",
    title: (cityContext: string) => `Projektanci wnętrz ${cityContext}`,
    heroIntro: (cityContext: string) => `Porównaj projektantów wnętrz i pracownie projektowe działające ${cityContext}.`,
    heroLeadSuffix: "Sprawdź portfolio, zakres usług, specjalizacje i dostępność, zanim wyślesz dobrze przygotowany brief.",
    viewProfessionals: (cityOrigin: string) => `Zobacz projektantów ${cityOrigin}`,
    createBrief: "Utwórz brief z pomocą AI",
    localDirectoryEyebrow: "Lokalny katalog",
    professionalsHeading: (cityContext: string) => `Specjaliści działający ${cityContext}`,
    professionalsCount: (count: number) => `${count} ${count === 1 ? "specjalista" : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 10 || count % 100 >= 20) ? "specjaliści" : "specjalistów"}`,
    studio: "Pracownia projektowa",
    designer: "Projektant wnętrz",
    designerFallback: "Projektant ArchiCompass",
    profileFallback: (cityContext: string) => `Zobacz profil, portfolio i realizacje tego projektanta ${cityContext}.`,
    viewProfile: "Zobacz profil i portfolio",
    emptyTitle: (cityContext: string) => `Katalog projektantów ${cityContext} już wkrótce.`,
    emptyBody: "Projektanci mogą już tworzyć profile dla tej lokalizacji. Strona pojawi się w publicznym indeksie wyszukiwania po opublikowaniu pierwszego lokalnego profilu.",
    joinCta: "Dołącz jako projektant lub pracownia",
    marketTitle: (city: string) => `Rynek projektowania wnętrz · ${city}`,
    planningTitle: "Co warto porównać",
    styleTitle: "Styl i dopasowanie portfolio",
    beforeContactEyebrow: "Zanim skontaktujesz się z projektantem",
    beforeContactTitle: "Dobry brief pomaga otrzymać trafniejsze odpowiedzi.",
    beforeContactLeft: "Podaj typ i status nieruchomości, metraż, pomieszczenia objęte projektem, lokalizację, budżet, planowany termin oraz informację o wizualizacjach 3D i nadzorze.",
    beforeContactRight: "Dodaj kilka zdjęć inspiracji i krótko wyjaśnij, co dokładnie Ci się w nich podoba. ArchiCompass rozpozna powtarzające się cechy i zapisze wynik w tym samym briefie.",
    beforeContactCta: "Uruchom AI Project Compass",
    moreLocationsPoland: "Więcej projektantów w Polsce",
    moreLocationsCountry: (country: string) => `Więcej projektantów w kraju: ${country}`,
    relatedLocation: (city: string) => `Projektanci wnętrz · ${city}`,
  },
  en: {
    notFoundTitle: "Location not found",
    notFoundDescription: "This location is not available.",
    home: "Home",
    directory: "Designer Directory",
    directoryLink: "Browse designers",
    directoryBadge: "Designer Directory",
    title: (cityContext: string) => `Interior designers ${cityContext}`,
    heroIntro: (cityContext: string) => `Compare interior designers and design studios working ${cityContext}.`,
    heroLeadSuffix: "Review portfolios, services, specialisms, and availability before sending a well-prepared brief.",
    viewProfessionals: (cityOrigin: string) => `View designers ${cityOrigin}`,
    createBrief: "Create a brief with AI",
    localDirectoryEyebrow: "Local directory",
    professionalsHeading: (cityContext: string) => `Professionals working ${cityContext}`,
    professionalsCount: (count: number) => `${count} ${count === 1 ? "professional" : "professionals"}`,
    studio: "Design studio",
    designer: "Interior designer",
    designerFallback: "ArchiCompass designer",
    profileFallback: (cityContext: string) => `View this designer's profile, portfolio, and completed work ${cityContext}.`,
    viewProfile: "View profile and portfolio",
    emptyTitle: (cityContext: string) => `The designer directory ${cityContext} is coming soon.`,
    emptyBody: "Designers can already create profiles for this location. The page will be added to the public search index once the first local profile is published.",
    joinCta: "Join as a designer or studio",
    marketTitle: (city: string) => `Interior design market · ${city}`,
    planningTitle: "What to compare",
    styleTitle: "Style and portfolio fit",
    beforeContactEyebrow: "Before you contact a designer",
    beforeContactTitle: "A clear brief helps you receive more relevant answers.",
    beforeContactLeft: "Add the property type and status, floor area, rooms in scope, location, budget, timeline, and whether you need 3D visualisations or site supervision.",
    beforeContactRight: "Upload a few inspiration photos and briefly explain what you like about them. ArchiCompass identifies recurring cues and keeps the result in the same brief.",
    beforeContactCta: "Open AI Project Compass",
    moreLocationsPoland: "More designers in Poland",
    moreLocationsCountry: (country: string) => `More designers in ${country}`,
    relatedLocation: (city: string) => `Interior designers · ${city}`,
  },
} as const;

export function getCityDirectoryCopy(locale: SiteLocale = siteLocale) {
  return copy[locale];
}
