import { siteLocale, type SiteLocale } from "@/lib/site-locale";

const jobStatusLabels = {
  pl: {
    QUEUED: "W kolejce",
    FETCHING: "Przeszukujemy Twoją stronę",
    EXTRACTING: "Pobieramy znalezione zdjęcia",
    GROUPING: "Grupujemy zdjęcia w projekty",
    ANALYZING: "Analizujemy charakter projektów",
    BUILDING_PROFILE: "Budujemy Twój profil ArchiCompass",
    READY_FOR_REVIEW: "Gotowe do przeglądu",
    FAILED: "Coś poszło nie tak",
    PUBLISHED: "Opublikowano",
  },
  en: {
    QUEUED: "Queued",
    FETCHING: "Searching your website for projects",
    EXTRACTING: "Downloading the photos we found",
    GROUPING: "Grouping photos into projects",
    ANALYZING: "Analyzing the design character of each project",
    BUILDING_PROFILE: "Building your ArchiCompass profile",
    READY_FOR_REVIEW: "Ready for your review",
    FAILED: "Something went wrong",
    PUBLISHED: "Published",
  },
} as const;

const portfolioAutopilotCopyByLocale = {
  pl: {
    name: "Asystent portfolio AI",
    flow: {
      ariaLabel: "Postęp Asystenta portfolio AI",
      source: "Źródło portfolio",
      importing: "Import i analiza",
      review: "Weryfikacja i publikacja",
    },
    start: {
      eyebrow: "Nowość",
      title: "Zbuduj swój profil z pomocą AI",
      intro:
        "Wskaż swoją stronę z portfolio lub dodaj zdjęcia ręcznie. ArchiCompass pogrupuje je w projekty, przeanalizuje charakter Twojej pracy i przygotuje szkic profilu — Ty go tylko sprawdzisz.",
      timeNote: "To zajmuje kilka minut. Zanim cokolwiek stanie się publiczne, wszystko sprawdzisz i zatwierdzisz.",
      illustrationAlt: "Podaj adres strony, a AI znajdzie zdjęcia i przygotuje profil",
      sourceTypeLabel: "Skąd wziąć zdjęcia?",
      sourceWebsite: "Strona internetowa lub portfolio online",
      sourceUpload: "Wgraj zdjęcia ręcznie",
      websiteUrlLabel: "Adres strony z portfolio",
      websiteUrlPlaceholder: "np. twojapracownia.pl/portfolio",
      websiteUrlHint: "Obsługujemy zwykłe strony WWW. Behance i Houzz — eksperymentalnie.",
      uploadLabel: "Zdjęcia projektów",
      uploadHint: (max: number) => `Do ${max} zdjęć naraz (JPG, PNG lub WebP).`,
      rightsLabel:
        "Potwierdzam, że mam prawo do wykorzystania tych zdjęć i upoważniam ArchiCompass do ich przetworzenia w celu stworzenia i dopasowania mojego profilu zawodowego.",
      submit: "Stwórz mój profil z AI",
      submitBusy: "Uruchamiamy import…",
      errors: {
        unauthenticated: "Zaloguj się jako projektant, aby skorzystać z tej funkcji.",
        rightsRequired: "Potwierdź prawa do zdjęć, aby kontynuować.",
        sourceRequired: "Podaj adres strony lub wgraj przynajmniej jedno zdjęcie.",
        invalidUrl: "Podaj prawidłowy adres strony (zaczynający się od http:// lub https://).",
        tooManyFiles: (max: number) => `Możesz wgrać maksymalnie ${max} zdjęć naraz.`,
        unsupportedFiles: "Wybierz zdjęcia JPG, PNG lub WebP, maksymalnie 10 MB każde.",
        genericFailure: "Nie udało się uruchomić importu. Spróbuj ponownie.",
      },
    },
    importing: {
      title: "Importujemy Twoje portfolio",
      illustrationAlt: "Dodaj adres strony, AI znajdzie zdjęcia i przygotuje profil",
      statusLabels: jobStatusLabels.pl,
      estimatedTime: "Zwykle zajmuje to kilka minut. Przy bardzo dużym portfolio może potrwać dłużej.",
      elapsedTime: (value: string) => `Czas importu: ${value}`,
      keepOpenHint: "Możesz zamknąć tę stronę lub zablokować telefon — import będzie kontynuowany w tle. Gdy będzie gotowy do przeglądu, wyślemy Ci e-mail.",
      previewTitle: "Znalezione zdjęcia",
      stageLabels: {
        QUEUED: "Przygotowujemy import",
        FETCHING: "Przeszukujemy portfolio",
        EXTRACTING: "Pobieramy zdjęcia",
        GROUPING: "Porządkujemy projekty",
        ANALYZING: "Analizujemy wnętrza",
        BUILDING_PROFILE: "Przygotowujemy profil",
        READY_FOR_REVIEW: "Gotowe do weryfikacji",
      },
      imagesFound: (count: number) => `Znaleziono ${count} zdjęć`,
      projectsFound: (count: number) => `Wykryto ${count} projektów`,
      failedTitle: "Import się nie powiódł",
      failedHelp: "Nie udało się dokończyć importu. Sprawdź adres strony lub połączenie z internetem i spróbuj ponownie.",
      connectionError: "Połączenie zostało przerwane. Sprawdź internet i spróbuj ponownie.",
      stillProcessing: "Import trwa dłużej niż zwykle. Odśwież stronę — wznowimy go od ostatniego kroku.",
      stalledTitle: "Import potrzebuje więcej czasu",
      stalledHelp: "Twoje portfolio nadal jest przetwarzane w tle. Możesz wrócić później — gdy import będzie gotowy, wyślemy Ci e-mail.",
      retryCta: "Spróbuj ponownie",
      backCta: "Wróć do startu",
      resumeCta: "Sprawdź status",
      manualUploadCta: "Dodaj zdjęcia ręcznie",
      continueCta: "Przejdź do przeglądu",
    },
    review: {
      title: "Twój profil jest prawie gotowy",
      subtitle: "Sprawdź, co znalazło AI. Możesz edytować, ukryć lub wyróżnić każdy projekt przed publikacją.",
      access: {
        title: "Otwórz import na właściwym koncie",
        body: "Ten import jest przypisany do konta, z którego został uruchomiony. Aby zachować prywatność portfolio, zaloguj się na to samo konto przed przejściem do przeglądu.",
        loginCta: "Zmień konto i zaloguj się",
        switchingAccount: "Wylogowywanie...",
        studioCta: "Wróć do Studio projektanta",
        hint: "Jeśli jesteś już zalogowany(-a), wybierz pierwszą opcję i zaloguj się na konto, z którego uruchomiono import.",
      },
      dna: {
        title: "Twój profil projektowy",
        primaryStyleLabel: "główny kierunek",
        secondaryStyleLabel: "silna cecha",
        materialsLabel: "Materiały",
        colorsLabel: "Kolory",
        roomsLabel: "Doświadczenie w pomieszczeniach",
        attributeLabels: {
          minimalism: "Minimalizm",
          warmth: "Ciepło",
          colorfulness: "Kolorowość",
          ornamentation: "Zdobienia",
          luxury: "Luksus",
        },
        evidenceLabel: (count: number) => `Na podstawie ${count} przeanalizowanych projektów`,
        empty: "Analiza AI jeszcze się nie zakończyła — profil pojawi się tutaj za chwilę.",
      },
      portfolioTitle: "Projekty",
      notInteriorProject: "AI: to nie wygląda na projekt wnętrza, domyślnie ukryte",
      keep: "Zachowaj",
      hide: "Ukryj",
      featured: "Wyróżnij",
      unfeature: "Usuń wyróżnienie",
      editTitlePlaceholder: "Nazwa projektu",
      confidenceHigh: "AI jest pewne grupowania",
      confidenceMedium: "Warto sprawdzić grupowanie",
      confidenceLow: "Niska pewność — sprawdź grupowanie",
      noPhotosWarning: "Ten projekt nie ma żadnych zdjęć. Dodaj zdjęcia albo ukryj ten projekt.",
      objectTypeLabels: {
        apartment: "Mieszkanie",
        house: "Dom",
        attic: "Poddasze",
        townhouse: "Kamienica",
        villa: "Willa",
        loft: "Loft",
        office: "Biuro",
        commercial: "Lokal",
      } as Record<string, string>,
      projectStageLabels: { realized: "Realizacja", concept: "Projekt koncepcyjny" } as Record<string, string>,
      areaLabel: (m2: number) => `${m2} m²`,
      aiTitlePrefix: "AI:",
      originalDescriptionLabel: "Opis ze strony źródłowej",
      roomTypesLabel: "Pomieszczenia",
      addTagPlaceholder: "Dodaj tag i naciśnij Enter",
      removeTagLabel: (tag: string) => `Usuń tag ${tag}`,
      descriptionLabel: "Opis",
      descriptionPlaceholder: "Dodaj opis tego projektu…",
      addPhotoLabel: "Dodaj zdjęcie",
      uploadingPhoto: "Wysyłanie…",
      deletePhotoLabel: "Usuń zdjęcie",
      openPhotoLabel: "Otwórz zdjęcie w pełnym rozmiarze",
      closePhotoLabel: "Zamknij podgląd zdjęcia",
      addPhotoError: "Nie udało się dodać zdjęcia.",
      deletePhotoError: "Nie udało się usunąć zdjęcia.",
      saveFailed: "Nie udało się zapisać tej zmiany. Odśwież stronę i spróbuj ponownie.",
      photoCount: (count: number) => `${count} zdjęć`,
      showAllPhotos: "Pokaż wszystkie zdjęcia",
      collapsePhotos: "Zwiń zdjęcia",
      publishCta: "Opublikuj profil",
      publishBusy: "Publikujemy…",
      publishedTitle: "Opublikowano!",
      publishedBody: "Twoje projekty są teraz widoczne na Twoim publicznym profilu ArchiCompass.",
      viewProfileCta: "Zobacz swój profil",
      analyzingNote: "Trwa analiza AI dla części projektów — odśwież za chwilę.",
      noKeptProjects: "Zachowaj przynajmniej jeden projekt, aby opublikować.",
      publishFailed: "Publikacja się nie powiodła. Spróbuj ponownie.",
      profileDraftCta: "Zobacz sugestie profilu",
    },
    profileDraft: {
      title: "Sugestie do Twojego profilu",
      subtitle:
        "ArchiCompass przygotował szkic na podstawie Twojego portfolio. Nic nie trafi na Twój publiczny profil, dopóki nie klikniesz „Opublikuj”.",
      empty: "Nie udało się przygotować sugestii dla tego importu.",
      sourceAiSuggestion: "Sugestia AI",
      sourceFoundOnSite: "Znaleziono na Twojej stronie",
      basicInfoTitle: "Dane podstawowe",
      aboutYouTitle: "O Tobie i Twojej pracowni",
      fullNameLabel: "Imię i nazwisko / nazwa pracowni",
      locationLabel: "Lokalizacja",
      emailLabel: "E-mail",
      phoneLabel: "Telefon",
      languagesLabel: "Języki",
      workModesLabel: "Formy współpracy",
      headlineLabel: "Nagłówek",
      aboutLabel: "O mnie",
      specialtiesLabel: "Specjalizacje",
      servicesLabel: "Usługi",
      servicesFoundOnSite: "Znalezione na stronie",
      servicesAiSuggested: "Sugestia AI na podstawie zdjęć",
      servicesConfirmYourself: "Nie widać na zdjęciach — potwierdź sam",
      socialsLabel: "Znalezione linki społecznościowe",
      alreadySetNote: "Masz już to pole uzupełnione — publikacja go nie zmieni.",
      savedInProfileBadge: "Zapisane w profilu",
      existingProfileHint: "Pola zapisane już w Twoim profilu pokazujemy tu tylko do odczytu. Zmienisz je w edycji profilu.",
      publishCta: "Opublikuj do mojego profilu",
      publishBusy: "Publikujemy…",
      publishedSummary: (applied: number, skipped: number) =>
        skipped > 0
          ? `Zaktualizowano ${applied} pól. ${skipped} pól pominięto, bo już były uzupełnione — edytuj je ręcznie w profilu, jeśli chcesz je zmienić.`
          : `Zaktualizowano ${applied} pól w Twoim profilu.`,
      publishFailed: "Publikacja profilu się nie powiodła. Spróbuj ponownie.",
      saveFailed: "Nie udało się zapisać tej zmiany. Odśwież stronę i spróbuj ponownie.",
      viewProfileEditCta: "Otwórz edycję profilu",
      backToReview: "Wróć do przeglądu projektów",
      editHint: "Możesz edytować każde pole przed publikacją.",
      nextStepsCta: "Zobacz, co jeszcze zostało",
    },
    nextSteps: {
      eyebrow: "Kolejne kroki",
      title: (score: number) => `Profil gotowy w ${score}%`,
      summary: (ready: number, toConfirm: number, toComplete: number) =>
        `${ready} informacji gotowych · ${toConfirm} wymaga potwierdzenia · ${toComplete} trzeba uzupełnić ręcznie.`,
      toConfirmTitle: "Potwierdź informacje",
      toCompleteTitle: "Uzupełnij ręcznie",
      confirmCta: "Otwórz edycję profilu",
      completeCta: "Uzupełnij w profilu",
      allDoneNote: "Twój profil jest kompletny. Świetna robota!",
      fieldLabels: {
        full_name: "Imię i nazwisko / nazwa pracowni",
        location: "Lokalizacja",
        profession_type: "Specjalizacja zawodowa",
        email: "E-mail",
        bio: "O mnie",
        profile_headline: "Nagłówek",
        specialties: "Specjalizacje",
        service_capabilities: "Usługi",
        pricing_model: "Model rozliczenia",
        price_range: "Cena od / do",
        work_modes: "Formaty pracy",
        availability_status: "Dostępność",
        years_experience: "Lata doświadczenia",
      },
    },
    admin: {
      title: "Importy portfolio",
      intro: "Lista importów Asystenta portfolio AI ze wszystkich kont projektantów.",
      retryCta: "Ponów",
      columns: {
        designer: "Projektant",
        source: "Źródło",
        status: "Status",
        images: "Zdjęcia",
        projects: "Projekty",
        created: "Utworzono",
      },
    },
  },
  en: {
    name: "AI Portfolio Assistant",
    flow: {
      ariaLabel: "AI Portfolio Assistant progress",
      source: "Portfolio source",
      importing: "Import and analysis",
      review: "Review and publish",
    },
    start: {
      eyebrow: "New",
      title: "Build your profile with AI",
      intro:
        "Point us to your portfolio website, or upload photos manually. ArchiCompass will group them into projects, analyze your design character, and prepare a draft profile - you just review it.",
      timeNote: "It takes a few minutes. You review and approve everything before anything becomes public.",
      illustrationAlt: "Add your website address and AI finds photos and prepares your profile",
      sourceTypeLabel: "Where should we get your photos?",
      sourceWebsite: "Website or online portfolio",
      sourceUpload: "Upload photos manually",
      websiteUrlLabel: "Portfolio website address",
      websiteUrlPlaceholder: "e.g. yourstudio.com/portfolio",
      websiteUrlHint: "Works with regular websites. Behance and Houzz are experimental.",
      uploadLabel: "Project photos",
      uploadHint: (max: number) => `Up to ${max} photos at once (JPG, PNG or WebP).`,
      rightsLabel:
        "I confirm that I have the right to use these images and authorize ArchiCompass to process them for creating and matching my professional profile.",
      submit: "Create my profile with AI",
      submitBusy: "Starting the import…",
      errors: {
        unauthenticated: "Sign in as a designer to use this feature.",
        rightsRequired: "Confirm your rights to these images to continue.",
        sourceRequired: "Enter a website address or upload at least one photo.",
        invalidUrl: "Enter a valid website address (starting with http:// or https://).",
        tooManyFiles: (max: number) => `You can upload up to ${max} photos at once.`,
        unsupportedFiles: "Choose JPG, PNG, or WebP images, up to 10 MB each.",
        genericFailure: "Could not start the import. Please try again.",
      },
    },
    importing: {
      title: "Importing your portfolio",
      illustrationAlt: "Add your website address, AI finds photos and prepares your profile",
      statusLabels: jobStatusLabels.en,
      estimatedTime: "This usually takes a few minutes. Very large portfolios can take longer.",
      elapsedTime: (value: string) => `Import time: ${value}`,
      keepOpenHint: "You can close this page or lock your phone — the import will continue in the background. We’ll email you when it is ready for review.",
      previewTitle: "Photos found",
      stageLabels: {
        QUEUED: "Preparing the import",
        FETCHING: "Searching your portfolio",
        EXTRACTING: "Downloading photos",
        GROUPING: "Organizing projects",
        ANALYZING: "Analyzing interiors",
        BUILDING_PROFILE: "Preparing your profile",
        READY_FOR_REVIEW: "Ready for review",
      },
      imagesFound: (count: number) => `${count} photos found`,
      projectsFound: (count: number) => `${count} projects detected`,
      failedTitle: "The import failed",
      failedHelp: "We couldn’t finish importing your portfolio. Check the website address or your internet connection and try again.",
      connectionError: "The connection was interrupted. Check your internet connection and try again.",
      stillProcessing: "The import is taking longer than usual. Refresh the page and we’ll continue from the last completed step.",
      stalledTitle: "Your import needs more time",
      stalledHelp: "Your portfolio is still being processed in the background. You can return later — we’ll email you when it is ready for review.",
      retryCta: "Try again",
      backCta: "Back to start",
      resumeCta: "Check status",
      manualUploadCta: "Add photos manually",
      continueCta: "Go to review",
    },
    review: {
      title: "Your profile is almost ready",
      subtitle: "Check what the AI found. You can edit, hide, or feature any project before publishing.",
      access: {
        title: "Open this import from the right account",
        body: "This import belongs to the account that started it. To keep the portfolio private, sign in to that same account before opening the review.",
        loginCta: "Switch account and sign in",
        switchingAccount: "Signing out...",
        studioCta: "Back to Designer Studio",
        hint: "If you are already signed in, choose the first option and sign in to the account that started the import.",
      },
      dna: {
        title: "Your design profile",
        primaryStyleLabel: "primary direction",
        secondaryStyleLabel: "strong trait",
        materialsLabel: "Materials",
        colorsLabel: "Colors",
        roomsLabel: "Room experience",
        attributeLabels: {
          minimalism: "Minimalism",
          warmth: "Warmth",
          colorfulness: "Colorfulness",
          ornamentation: "Ornamentation",
          luxury: "Luxury",
        },
        evidenceLabel: (count: number) => `Based on ${count} analyzed projects`,
        empty: "AI analysis hasn't finished yet - your profile will appear here shortly.",
      },
      portfolioTitle: "Projects",
      notInteriorProject: "AI: this doesn't look like an interior project, hidden by default",
      keep: "Keep",
      hide: "Hide",
      featured: "Feature",
      unfeature: "Remove feature",
      editTitlePlaceholder: "Project name",
      confidenceHigh: "AI is confident in this grouping",
      confidenceMedium: "Worth double-checking this grouping",
      confidenceLow: "Low confidence - double-check this grouping",
      noPhotosWarning: "This project has no photos. Add photos or hide this project.",
      objectTypeLabels: {
        apartment: "Apartment",
        house: "House",
        attic: "Attic",
        townhouse: "Townhouse",
        villa: "Villa",
        loft: "Loft",
        office: "Office",
        commercial: "Commercial unit",
      } as Record<string, string>,
      projectStageLabels: { realized: "Realized", concept: "Concept project" } as Record<string, string>,
      areaLabel: (m2: number) => `${m2} m²`,
      aiTitlePrefix: "AI:",
      originalDescriptionLabel: "Description from the source page",
      roomTypesLabel: "Rooms",
      addTagPlaceholder: "Add a tag and press Enter",
      removeTagLabel: (tag: string) => `Remove tag ${tag}`,
      descriptionLabel: "Description",
      descriptionPlaceholder: "Add a description for this project…",
      addPhotoLabel: "Add photo",
      uploadingPhoto: "Uploading…",
      deletePhotoLabel: "Delete photo",
      openPhotoLabel: "Open photo at full size",
      closePhotoLabel: "Close photo preview",
      addPhotoError: "Could not add the photo.",
      deletePhotoError: "Could not delete the photo.",
      saveFailed: "We couldn’t save this change. Refresh the page and try again.",
      photoCount: (count: number) => `${count} photos`,
      showAllPhotos: "Show all photos",
      collapsePhotos: "Collapse photos",
      publishCta: "Publish profile",
      publishBusy: "Publishing…",
      publishedTitle: "Published!",
      publishedBody: "Your projects are now visible on your public ArchiCompass profile.",
      viewProfileCta: "View your profile",
      analyzingNote: "AI analysis is still running for some projects - refresh in a moment.",
      noKeptProjects: "Keep at least one project to publish.",
      publishFailed: "Publishing failed. Please try again.",
      profileDraftCta: "View profile suggestions",
    },
    profileDraft: {
      title: "Suggestions for your profile",
      subtitle:
        "ArchiCompass drafted this from your portfolio. Nothing goes to your public profile until you click \"Publish\".",
      empty: "We couldn't prepare suggestions for this import.",
      sourceAiSuggestion: "AI suggestion",
      sourceFoundOnSite: "Found on your site",
      basicInfoTitle: "Basic information",
      aboutYouTitle: "About you and your studio",
      fullNameLabel: "Name / studio name",
      locationLabel: "Location",
      emailLabel: "Email",
      phoneLabel: "Phone",
      languagesLabel: "Languages",
      workModesLabel: "Work modes",
      headlineLabel: "Headline",
      aboutLabel: "About",
      specialtiesLabel: "Specialties",
      servicesLabel: "Services",
      servicesFoundOnSite: "Found on your site",
      servicesAiSuggested: "AI suggestion based on your photos",
      servicesConfirmYourself: "Not visible in photos — confirm yourself",
      socialsLabel: "Social links found",
      alreadySetNote: "You already have this field filled in — publishing won't change it.",
      savedInProfileBadge: "Saved in profile",
      existingProfileHint: "Fields already saved in your profile are shown here as read-only. Edit them in your profile editor.",
      publishCta: "Publish to my profile",
      publishBusy: "Publishing…",
      publishedSummary: (applied: number, skipped: number) =>
        skipped > 0
          ? `Updated ${applied} field${applied === 1 ? "" : "s"}. Skipped ${skipped} that were already filled in - edit them manually in your profile if you want to change them.`
          : `Updated ${applied} field${applied === 1 ? "" : "s"} on your profile.`,
      publishFailed: "Publishing your profile update failed. Please try again.",
      saveFailed: "We couldn’t save this change. Refresh the page and try again.",
      viewProfileEditCta: "Open profile editor",
      backToReview: "Back to project review",
      editHint: "You can edit any field before publishing.",
      nextStepsCta: "See what's left",
    },
    nextSteps: {
      eyebrow: "Next steps",
      title: (score: number) => `Profile ${score}% ready`,
      summary: (ready: number, toConfirm: number, toComplete: number) =>
        `${ready} field${ready === 1 ? "" : "s"} ready · ${toConfirm} need${toConfirm === 1 ? "s" : ""} confirming · ${toComplete} to fill in manually.`,
      toConfirmTitle: "Confirm these",
      toCompleteTitle: "Fill in manually",
      confirmCta: "Open profile editor",
      completeCta: "Fill in on your profile",
      allDoneNote: "Your profile is complete. Nice work!",
      fieldLabels: {
        full_name: "Name / studio name",
        location: "Location",
        profession_type: "Professional specialization",
        email: "Email",
        bio: "About",
        profile_headline: "Headline",
        specialties: "Specialties",
        service_capabilities: "Services",
        pricing_model: "Pricing model",
        price_range: "Price from / to",
        work_modes: "Work modes",
        availability_status: "Availability",
        years_experience: "Years of experience",
      },
    },
    admin: {
      title: "Portfolio imports",
      intro: "AI Portfolio Assistant import jobs across all designer accounts.",
      retryCta: "Retry",
      columns: {
        designer: "Designer",
        source: "Source",
        status: "Status",
        images: "Photos",
        projects: "Projects",
        created: "Created",
      },
    },
  },
} as const;

export function getPortfolioAutopilotCopy(locale: SiteLocale = siteLocale) {
  return portfolioAutopilotCopyByLocale[locale];
}
