import { siteLocale, type SiteLocale } from "@/lib/site-locale";

const copy = {
  pl: {
    notFoundTitle: "Nie znaleziono projektu",
    notFoundDescription: "Ten projekt wnętrza nie jest dostępny.",
    projectFallback: "Projekt wnętrza",
    titleFallback: "Projekt bez tytułu",
    designerFallback: "Projektant ArchiCompass",
    designer: "Projektant wnętrz",
    studio: "Pracownia projektowa",
    directory: "Katalog Projektantów",
    portfolio: "Portfolio",
    portfolioProject: "Projekt portfolio",
    backToPortfolio: "Wróć do portfolio projektanta",
    backToInspiration: "Wróć do Inspiration Hub",
    manageProject: "Zarządzaj tym projektem",
    demoProject: "Przykładowy projekt portfolio",
    publicDescription: "Publiczna strona projektu w ArchiCompass z galerią, informacjami o autorze i kontekstem realizacji.",
    projectInformation: "Informacje o projekcie",
    photos: "Zdjęcia",
    category: "Kategoria",
    projectStory: "Historia projektu",
    details: "Szczegóły",
    detailsFallback: "Ten projekt może zostać uzupełniony o brief, cele, materiały, rodzaj pomieszczeń, zakres i opis efektu dla klienta.",
    externalProject: "Otwórz zewnętrzną stronę projektu",
    viewPortfolio: "Zobacz portfolio projektanta",
    location: "Lokalizacja",
    remoteLocation: "Zdalnie / lokalizacja do ustalenia",
    project: "Projekt",
    sharing: "Udostępnianie",
    copyAddress: "Skopiuj adres tej strony",
    viewDesigner: "Otwórz profil projektanta",
    editAccount: "Edytuj w swoim koncie",
    sendBrief: "Wyślij brief projektantowi",
    designerAccountNote: "Konta projektantów otrzymują briefy i nie mogą wysyłać zapytań klientów.",
    openWebsite: "Otwórz stronę internetową",
    metadataDescription: (category: string) => `Zobacz projekt, galerię i profil autora w ArchiCompass. Kategoria: ${category}.`,
  },
  en: {
    notFoundTitle: "Project not found",
    notFoundDescription: "This interior project is not available.",
    projectFallback: "Interior project",
    titleFallback: "Untitled project",
    designerFallback: "ArchiCompass designer",
    designer: "Interior designer",
    studio: "Design studio",
    directory: "Designer Directory",
    portfolio: "Portfolio",
    portfolioProject: "Portfolio project",
    backToPortfolio: "Back to the designer's portfolio",
    backToInspiration: "Back to Inspiration Hub",
    manageProject: "Manage this project",
    demoProject: "Sample portfolio project",
    publicDescription: "A public ArchiCompass project page with a gallery, author details, and project context.",
    projectInformation: "Project information",
    photos: "Photos",
    category: "Category",
    projectStory: "Project story",
    details: "Details",
    detailsFallback: "This project can be expanded with its brief, goals, materials, rooms, scope, and a clear description of the intended result for the client.",
    externalProject: "Open the external project page",
    viewPortfolio: "View the designer's portfolio",
    location: "Location",
    remoteLocation: "Remote / location to be agreed",
    project: "Project",
    sharing: "Sharing",
    copyAddress: "Copy this page address",
    viewDesigner: "Open designer profile",
    editAccount: "Edit in your account",
    sendBrief: "Send a brief to this designer",
    designerAccountNote: "Designer accounts receive briefs and cannot send client enquiries.",
    openWebsite: "Open website",
    metadataDescription: (category: string) => `View the project, gallery, and creator profile on ArchiCompass. Category: ${category}.`,
  },
} as const;

export function getProjectDetailCopy(locale: SiteLocale = siteLocale) {
  return copy[locale];
}
