export const designerStyles = [
  "Art Deco",
  "Bohemian",
  "Contemporary",
  "Dopamine decor",
  "Eclectic",
  "Glamour",
  "Industrial",
  "Japandi",
  "Mediterranean",
  "Mid-century modern",
  "Minimalist",
  "Minimaluxe",
  "Modern",
  "Quiet luxury",
  "Rustic",
  "Scandinavian",
  "Soft minimalism",
  "Traditional",
  "Vintage",
] as const;

export const projectServiceCategories = [
  "Whole home or apartment",
  "Kitchen",
  "Living room",
  "Bathroom",
  "Bedroom",
  "Children's room",
  "Home office",
  "Commercial or hospitality",
  "Rental or investment property",
] as const;

export const specialistFocusOptions = [
  "Families with children",
  "Small spaces",
  "Large homes",
  "Accessible interiors",
  "Short-term rentals",
  "Smart homes",
  "Budget-conscious projects",
  "Sustainable design",
] as const;

const polishLabels: Record<string, string> = {
  "Art Deco": "art déco",
  Bohemian: "boho",
  Contemporary: "współczesny",
  "Dopamine decor": "dopamine decor",
  Eclectic: "eklektyczny",
  Glamour: "glamour",
  Industrial: "industrialny",
  Japandi: "japandi",
  Mediterranean: "śródziemnomorski",
  "Mid-century modern": "mid-century modern",
  Minimalist: "minimalistyczny",
  Minimaluxe: "minimaluxe",
  Modern: "nowoczesny",
  "Quiet luxury": "quiet luxury",
  Rustic: "rustykalny",
  Scandinavian: "skandynawski",
  "Soft minimalism": "soft minimalizm",
  Traditional: "tradycyjny",
  Vintage: "vintage",
  "Whole home or apartment": "cały dom lub mieszkanie",
  Kitchen: "kuchnia",
  "Living room": "salon",
  Bathroom: "łazienka",
  Bedroom: "sypialnia",
  "Children's room": "pokój dziecięcy",
  "Home office": "gabinet domowy",
  "Commercial or hospitality": "lokal komercyjny lub hotelarski",
  "Rental or investment property": "nieruchomość na wynajem lub inwestycyjna",
  "Families with children": "rodziny z dziećmi",
  "Small spaces": "małe przestrzenie",
  "Large homes": "duże domy i mieszkania",
  "Accessible interiors": "wnętrza dostępne",
  "Short-term rentals": "najem krótkoterminowy",
  "Smart homes": "inteligentne domy",
  "Budget-conscious projects": "projekty z kontrolowanym budżetem",
  "Sustainable design": "zrównoważone projektowanie",
  Apartment: "mieszkanie",
  House: "dom",
  Office: "biuro",
  "Single room": "pojedyncze pomieszczenie",
  Commercial: "wnętrze komercyjne",
  Hospitality: "hotel lub gastronomia",
  Restaurant: "restauracja",
  Retail: "lokal handlowy",
};

export function professionalOptionLabel(value: string) {
  return polishLabels[value] || value;
}
